### ISSUE TITLE
Can we please add an option to tell supertest to parse response.text to JSON?

### ISSUE THREAD

**Issue by freegink** [avbel/co-supertest#5]
Hi avbel,

Because one may use pure JSON APIs, it's more convenient to have the response body ready as JSON. Basically parse response.text as JSON and assign the result to response.body before passing the response to end().

I'm very happy to do a pull request if you like. Thanks

**Comment by avbel** [comment]
Sorry It is not good idea to treat response.text as json. If your service returns data with content type aaplication/json response.body will contain parsed data (supertest do that itself)
