### ISSUE TITLE
supertest 2.0.0

### ISSUE THREAD

**Issue by mderazon** [avbel/co-supertest#9]
Hi,

Supertest has upgraded to 2.0.0.
Nothing breaks co-supertest, just need to update package.json

**Comment by avbel** [comment]
This lib is not required more. Superagent and supertest support promises now. So you can use them without this lib with co.

```js
  yield request.get('/path').expect(200);
```

**Comment by mderazon** [comment]
Didn't know that, can you please direct me to where it's says in the documentation / issues ? Can't find anything

**Comment by avbel** [comment]
Supertest is based on `superagent`. Superagen now supports promises in the box. I.e. now you can use with superagent

``` js
request.get('/search').then(success, failure);
```

Supertest's `Request` inherits `Request` of superagent.  So you can use such code with supertest

``` js
 supertest(app).get('/search').expect(200).then(success, failure);

//with co 1.0
yield  supertest(app).get('/search').expect(200); //co can 'yield' any promise object

//with async/await (co 2+, TypeScript, ES7, etc)

await  supertest(app).get('/search').expect(200); //await can be used with promise objects only 
```

So `co-supertest` is not need for for Supertest 2+. I don't see any sense to support it.
